const resources = [
    {
      name: "Cruse Bereavement Support",
      image: `${process.env.PUBLIC_URL}/images/National/cruse.png`,
      description: "Provides support and counseling for those experiencing loss.",
      website: "https://www.cruse.org.uk",
      phone: "0808 808 1677",
      category: ["Bereavement"],
      tags: ["Mental Health", "Counselling", "Peer Support"],
      extraInfo: "Specialises in helping families and children cope with grief.",
    },
    {
      name: "PANDAS Foundation",
      image: `${process.env.PUBLIC_URL}/images/National/pandasfoundation.png`,
      description: "Support for perinatal mental health issues.",
      website: "https://pandasfoundation.org.uk",
      WhatsApp: "07903 508334",
      email: "supportme@pandasfoundation.org.uk",
      Facebook: "https://www.facebook.com/PANDASFoundation/",
      FacebookMumsGroup: "https://www.facebook.com/groups/PANDASClosedGroup/",
      FacebookDadsGroup: "https://www.facebook.com/groups/367885373581814/",
      category: ["Mental Health"],
      tags: ["Perinatal", "Support Groups", "Counselling"],
      extraInfo: "",
    },
    {
      name: "Acacia - Family Support",
      image: `${process.env.PUBLIC_URL}/images/National/Acacia.png`,
      description: "Acacia Family Support provides specialised services for families dealing with depression.",
      website: "https://www.acacia.org.uk/",
      phone: "0121 301 5990",
      category: ["Depression"],
      tags: ["Perinatal", "Postnatal", "Antenatal", "Support Groups", "Counselling", "Young Parents",],
      location: "Birmingham, UK",
    },
    {
        name: "Acacia - LGBTQ",
        image: `${process.env.PUBLIC_URL}/images/National/Acacialgbtq.png`,
        description: "The Acacia LGBTQ+ service focuses on providing support for LGBTQ+ parents who are navigating depression.",
        website: "https://www.acacia.org.uk/dads-partners/lgbtq",
        phone: "0121 301 5990",
        category: ["Depression"],
        tags: ["Perinatal", "Postnatal", "Antenatal", "Support Groups", "Counselling",],
        location: "Birmingham, UK",
    },
    {
        name: "Acacia - Dads & Partners",
        image: `${process.env.PUBLIC_URL}/images/National/Acaciadadspartners.png`,
        description: "Acacia Family Support provides specialised services for families dealing with depression.",
        website: "https://www.acacia.org.uk/dads-partners/",
        phone: "0121 301 5990",
        category: ["Depression"],
        tags: ["Support Groups", "Counselling","Dads","Partners",],
        location: "Birmingham, UK",
    },
    {
        name: "Petals",
        image: `${process.env.PUBLIC_URL}/images/National/petals.png`,
        description: "The baby loss counselling charity. Petals provide specialist counselling to parents after baby loss.",
        website: "https://www.petalscharity.org/",
        category: ["Baby Loss"],
        tags: ["Miscarriage", "Stillbirth","Pregnancy After Loss","Counselling",],
        location: "Colchester, Essex, UK",
    },
    {
        name: "Parents 1st Essex",
        image: `${process.env.PUBLIC_URL}/images/National/p1stessex.png`,
        description: "Offering life changing peer support for parents in Essex.",
        website: "https://parents1st.org.uk/parents-1st-essex",
        category: ["Peer Support"],
        tags: ["Workshops", "Antenatal","Online Classes","In Person Classes", "First Aid", "Dads", "Partners", "Empowerment",],
    },
    {
      name: "APP (Action on Postpartum Psychosis)",
      image: `${process.env.PUBLIC_URL}/images/National/app.png`,
      description: "Supporting and advocating for mums and families affected by postpartum psychosis (PP)",
      website: "https://www.app-network.org/",
      category: ["Postpartum Psychosis"],
      tags: ["Mental Health", "PP", "Dads", "Co-Parents",],
  },
  {
    name: "Baby Buddy App by best beginnings",
    image: `${process.env.PUBLIC_URL}/images/National/babybuddyapp.png`,
    description: "- For every parent, for every child",
    website: "https://www.bestbeginnings.org.uk/baby-buddy",
    text: "BABYBUDDY to 85258 for free anonymous support via text message.",
    category: ["Smartphone Application"],
    tags: ["Support", "Practical Help", "Co-Parents", "Dads", "Empowerment",  "Emotional Support",],
},
{
  name: "BBC Tiny Happy People",
  image: `${process.env.PUBLIC_URL}/images/National/bbctinyhappypeople.png`,
  description: "Find out all about your child's brain development and how they come to understand the world with BBC Tiny Happy People.",
  website: "https://www.bbc.co.uk/tiny-happy-people",
  facebook: "https://www.facebook.com/bbctinyhappypeople",
  category: ["Child Development"],
  tags: ["Advice", "Tips", "Activities",],
},
  ];
  
  export default resources;
  