const resources = [
    {
      name: "Cruse Bereavement Support",
      image: `${process.env.PUBLIC_URL}/images/National/cruse.png`,
      description: "Provides support and counseling for those experiencing loss.",
      website: "https://www.cruse.org.uk",
      email: "info@cruse.org.uk",
      category: ["Bereavement"],
      tags: ["Mental Health", "Counselling", "Peer Support"],
      extraInfo: "Specializes in helping families and children cope with grief.",
    },
    {
      name: "PANDAS Foundation",
      image: `${process.env.PUBLIC_URL}/images/National/pandasfoundation.png`,
      description: "Support for perinatal mental health issues.",
      website: "https://pandasfoundation.org.uk",
      landline: "01376 517393",
      mobile: "07956648211",
      email: "support@pandas.org.uk",
      category: ["Mental Health"],
      tags: ["Perinatal", "Support Groups", "Counselling"],
      extraInfo: "",
    },
    {
      name: "Acacia - Family Support",
      image: `${process.env.PUBLIC_URL}/images/National/acacia.png`,
      description: "Acacia Family Support provides specialised services for families dealing with depression.",
      website: "https://www.acacia.org.uk/",
      phone: "0121 301 5990",
      category: ["Depression"],
      tags: ["Perinatal", "Postnatal", "Antenatal", "Support Groups", "Counselling",],
      location: "Birmingham",
    },
    {
        name: "Acacia - LGBTQ",
        image: `${process.env.PUBLIC_URL}/images/National/acacialgbtq.png`,
        description: "The Acacia LGBTQ+ service focuses on providing support for LGBTQ+ parents who are navigating depression.",
        website: "https://www.acacia.org.uk/dads-partners/lgbtq",
        phone: "0121 301 5990",
        category: ["Depression"],
        tags: ["Perinatal", "Postnatal", "Antenatal", "Support Groups", "Counselling",],
        location: "Birmingham",
    },
    {
        name: "Acacia - Dads & Partners",
        image: `${process.env.PUBLIC_URL}/images/National/acaciadadspartners.png`,
        description: "Acacia Family Support provides specialised services for families dealing with depression.",
        website: "https://www.acacia.org.uk/dads-partners/",
        phone: "0121 301 5990",
        category: ["Depression"],
        tags: ["Support Groups", "Counselling","Dads","Partners",],
        location: "Birmingham",
    },
    {
        name: "Petals",
        image: `${process.env.PUBLIC_URL}/images/National/petals.png`,
        description: "The baby loss counselling charity. Petals provide specialist counselling to parents after baby loss.",
        website: "https://www.petalscharity.org/",
        category: ["Baby Loss"],
        tags: ["Miscarriage", "Stillbirth","Pregnancy After Loss","Counselling",],
        location: "Colchester, Essex",
    },
    {
        name: "Parents 1st Essex",
        image: `${process.env.PUBLIC_URL}/images/National/p1stessex.png`,
        description: "The baby loss counselling charity. Petals provide specialist counselling to parents after baby loss.",
        website: "https://www.petalscharity.org/",
        category: ["Baby Loss"],
        tags: ["Miscarriage", "Stillbirth","Pregnancy After Loss","Counselling",],
        location: "Colchester, Essex",
    },
  ];
  
  export default resources;
  